from swagger_server.exceptions.polygon_exceptions import CustomException